package net.ninjacat.omg.bytecode;

/**
 * This class is used to inspect generated bytecode
 * TODO: Delete
 */
public class GenTest {
    public GenTest() {

    }

    public boolean compare() {
        long i1 = 10L;
        long i2 = i1 * 2;
        return longCmp(i1, i2);
    }

    private boolean longCmp(long l1, long l2) {
        return l1 == l2;
    }
}
